---
engines:
  duplication:
    enabled: true
    exclude_fingerprints:
    - 6e77cde98fff9c92f5441e9c68a001a0
    - 2a68cff27d8dd8b6b2c2c71b43f3d80a
    - 237cb24fd42103d623c26dc71384ef33
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- confireadmeg/
- tests/
- app/templates/
- addon/templates/
- "README.md"
- "LICENSE.md"
- "changelog.md"
